### ISSUE TITLE
Point LNCR_ZIP_URL to official https://github.com/yuk7/wsldl

### ISSUE THREAD

**Issue by darcyparker** [sileshn/ManjaroWSL#1]
https://github.com/sileshn/ManjaroWSL/blob/main/Makefile#L6 references your fork of wsldl that adds the icons https://github.com/sileshn/wsldl/commit/082ba7a3f1f5f4f7c9441e68b877a57bbe96f632.

Do you have plans to create a pull request for the additional distros you created? And add your distros to https://wsldl-pg.github.io/docs/Using-wsldl/ ?

The reason I ask is that it would make it easier for users to quickly check your repo to make sure it feels 'safe' before I run the .exe on my machine.  I read https://github.com/sileshn/ManjaroWSL/blob/main/Makefile and it looks good. I just think it would be quicker to review if you retrieved images from the official wsldl repo rather than your fork.

Perhaps this is already on your todo list? so this is just a friendly reminder if it is.

Thanks for creating a manjaro distro for wsldl.

**Comment by darcyparker** [comment]
BTW: You should add your distros to https://github.com/sirredbeard/Awesome-WSL#unofficial-distributions

**Comment by sileshn** [comment]
Official wsldl repo doesn't have the manjaro icon. I will look into creating a PR as you suggested.

**Comment by sileshn** [comment]
@darcyparker All PR's done..
