### ISSUE TITLE
[ARM64] An error occurred

### ISSUE THREAD

**Issue by spindla** [sileshn/ManjaroWSL#10]
Hey,

i had execute the Manjaro.exe on my Surface Pro X on the latest Insider Build an i got this error:

`An error occurred mounting one of your file systems. Please run 'dmesg' for more details.
[process exited with code 1]`

What am I doing wrong? On my x64 machine works all fine!

**Comment by sileshn** [comment]
That's because its built for x64. Try the arm64 zip file from the latest release. I've added it and its untested.

**Comment by spindla** [comment]
Unfortunately this new version dosen't work. Same error:

`An error occurred mounting one of your file systems. Please run 'dmesg' for more details.`

**Comment by sileshn** [comment]
If you have followed all instructions from the link below and set wsl2 as default before install, I am not sure I can help as I don't use any ARM device.

**Comment by spindla** [comment]
I had followed the instructions from the link, it dosen't work. Ubuntu and Pengwin from the microsoft store works fine.
I would try to build this my self on my pro x but I don't have access to your gitlab source.

**Comment by spindla** [comment]
I was able to solve my problem. I built rootfs with an arm64 docker image.
