### ISSUE TITLE
Restore feature?

### ISSUE THREAD

**Issue by Sanczzg** [sileshn/ManjaroWSL#12]
Currently we can export the backup of Manjaro WSL and reg file, but there's no option to restore these backups through Manjaro.exe. Are we going to have this feature later on? And updating Manjaro.exe by itself.

**Comment by sileshn** [comment]
You'll have to check with yuk7.

https://github.com/yuk7/wsldl

**Comment by Sanczzg** [comment]
> You'll have to check with yuk7.
> 
> https://github.com/yuk7/wsldl

I found a similar issue from ArchWSL and here's the solution: https://github.com/yuk7/ArchWSL/issues/90#issuecomment-502092309

Hope everyone could see this!

**Comment by sileshn** [comment]
I'll add it to the readme file

**Comment by sileshn** [comment]
47bd8ccd79e9ca30548c1c914b5dd6da4a35ce75
