### ISSUE TITLE
exe issue

### ISSUE THREAD

**Issue by PeterKW** [sileshn/ManjaroWSL#14]
Using: C:\Program Files\Manjaro\rootfs.tar.gz
Installing...
ERROR:Installation Failed!
HRESULT:0x80070005
Press any key to continue...

Any idea what I should try next? WSL is definitely enabled

**Comment by sileshn** [comment]
Need more info.

Which windows version?
Is wsl2 set as default?
Is wsl kernel installed?

**Comment by PeterKW** [comment]
Windows 10
I reset wsl2 as default again hopefully before this
I assume the kernel is installed as Ubuntu is working?
Sorry, I may be misunderstanding something

**Comment by PeterKW** [comment]
Anything else that I could try @sileshn?

**Comment by sileshn** [comment]
What's the output of wsl -l -v

**Comment by PeterKW** [comment]
Hopefully got it working. I'm only on Beta Release of Windows 10 as I didn't want to move to 11 on my main device so I believe gWSL for running linux GUI applications doesn't work with Manjaro yet but hopefully will be using that more when it comes out

wsl -l -v
  NAME                   STATE           VERSION
* Ubuntu                 Stopped         2
  docker-desktop-data    Stopped         2
  docker-desktop         Stopped         2
  Arch                   Stopped         2
  Manjaro                Running         2
