### ISSUE TITLE
WSLg

### ISSUE THREAD

**Issue by 5wattbulb** [sileshn/ManjaroWSL#15]
### Requirements

- [X] Yes
- [ ] No

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Windows Build Number

Microsoft Windows [Version 10.0.22000.120]

### Kernel Version

5.10.43

### Repro Steps

Install gedit & start from windows terminal manajaro tab.

### Expected Behavior

In my limited experimentation it does seem to work but the terminal spews out a string of errors and warnings most of which are duplicates (output shown below). You can avoid that ugliness by starting the app from the windows start menu. I was just wondering if you've experimented much with WSLg yourself and how good / bad it was with manjaro?

PS Thanks for this.

### Actual Behavior

[tom@sp4 ~]$ gedit

(gedit:161): dconf-CRITICAL **: 12:51:26.665: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.665: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.665: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.665: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.665: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.666: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.666: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.666: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.666: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.666: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.666: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.667: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.670: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.676: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.676: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-WARNING **: 12:51:26.676: failed to commit changes to dconf: Cannot spawn a message bus without a machine-id: Unable to load /var/lib/dbus/machine-id or /etc/machine-id: Failed to open file “/var/lib/dbus/machine-id”: No such file or directory

(gedit:161): dconf-CRITICAL **: 12:51:26.683: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.683: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.683: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.683: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-WARNING **: 12:51:26.684: failed to commit changes to dconf: Cannot spawn a message bus without a machine-id: Unable to load /var/lib/dbus/machine-id or /etc/machine-id: Failed to open file “/var/lib/dbus/machine-id”: No such file or directory

(gedit:161): dconf-CRITICAL **: 12:51:26.718: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.763: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.763: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.763: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.763: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.764: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.764: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.764: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.764: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.764: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.764: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.778: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.779: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.780: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.781: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.781: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.783: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.783: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.783: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.785: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.786: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.786: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.819: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.819: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.827: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.827: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.827: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.827: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.827: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.841: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.841: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.842: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.844: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.844: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.844: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.844: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.844: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.844: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.844: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.844: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.844: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.848: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.849: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.849: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.849: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.849: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.849: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

** (gedit:161): WARNING **: 12:51:26.849: Error loading plugin: libhunspell-1.7.so.0: cannot open shared object file: No such file or directory

** (gedit:161): WARNING **: 12:51:26.850: Error loading plugin: libhspell.so.0: cannot open shared object file: No such file or directory

** (gedit:161): WARNING **: 12:51:26.850: Error loading plugin: libaspell.so.15: cannot open shared object file: No such file or directory

** (gedit:161): WARNING **: 12:51:26.850: Error loading plugin: libvoikko.so.1: cannot open shared object file: No such file or directory

** (gedit:161): WARNING **: 12:51:26.850: Error loading plugin: libnuspell.so.5: cannot open shared object file: No such file or directory

** (gedit:161): WARNING **: 12:51:26.853: Error loading plugin: libhunspell-1.7.so.0: cannot open shared object file: No such file or directory

** (gedit:161): WARNING **: 12:51:26.853: Error loading plugin: libhspell.so.0: cannot open shared object file: No such file or directory

** (gedit:161): WARNING **: 12:51:26.853: Error loading plugin: libaspell.so.15: cannot open shared object file: No such file or directory

** (gedit:161): WARNING **: 12:51:26.853: Error loading plugin: libvoikko.so.1: cannot open shared object file: No such file or directory

** (gedit:161): WARNING **: 12:51:26.860: Error loading plugin: libnuspell.so.5: cannot open shared object file: No such file or directory

(gedit:161): dconf-CRITICAL **: 12:51:26.862: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.871: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.875: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:26.875: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:30.519: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:30.521: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:30.522: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:30.522: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:30.522: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:30.523: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:30.524: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-CRITICAL **: 12:51:30.524: unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly.

(gedit:161): dconf-WARNING **: 12:51:30.524: failed to commit changes to dconf: Cannot spawn a message bus without a machine-id: Unable to load /var/lib/dbus/machine-id or /etc/machine-id: Failed to open file “/var/lib/dbus/machine-id”: No such file or directory
[tom@sp4 ~]$

**Comment by sileshn** [comment]
No. I haven't yet tried out wslg. I will investigate and let u know

**Comment by 5wattbulb** [comment]
No, unless updating wsl after joining the windows insider programme did it automatically for me. I certainly couldn't get gedit to work from the  command line in Ubuntu prior to that.

**Comment by sileshn** [comment]
You need special GPU drivers for wslg to work. Please go thru the readme page at Microsoft wslg github page for link to the drivers and try if it works properly.

**Comment by 5wattbulb** [comment]
Thanks sileshn. Will try first thing in morning (20:00 here) and let you know how I got on.

**Comment by sileshn** [comment]
Run the following command and you should see only
![Screenshot 2021-08-09 145615](https://user-images.githubusercontent.com/977360/128685545-aca843b2-85dd-47a5-a54d-98edf74b45bb.png)
 the machine-id warning. That is related to systemd. As ManjaroWSL doesn't support systemd OOTB, you need to look at other ways to enable it, like https://github.com/arkane-systems/genie.

sudo pacman -S aspell hspell hunspell nuspell libvoikko dconf

**Comment by 5wattbulb** [comment]
Tried installing the intel graphics driver installer at https://www.intel.com/content/www/us/en/download/19344/30579/intel-graphics-windows-dch-drivers.html but got error "Your system has a driver that is locked to manufacturer specifications...". It did say at https://devblogs.microsoft.com/commandline/wslg-architecture/#hardware-accelerated-opengl that eventually Windows Update will update the driver.

Looking at genie just now but it's a bit overwhelming as I've only been using linux 6 months.

**Comment by 5wattbulb** [comment]
genie looks over my head shiles. The thing is, I'm not even sure what I'm expecting at the end of it. gEdit to run without error messages?

**Comment by sileshn** [comment]
Not really. It depends on what you are using wsl for. If it is only to run a few apps like gedit, then you don't need to bother about systemd. I don't need it either as I use wsl only for android development. 

My replies were based on the assumption that you were bothered by the slew of warnings that showed up. If not, then I don't understand the reason why you opened this issue.

**Comment by 5wattbulb** [comment]
It wasn't so much an issue as much as determining if I should really expect WSLg to work with manjaro and, if so, was there a simple solution to the error messages. I may yet install genie if I come across bigger problems but I'm in no rush at present as I'll be mainly working in terminal. Thanks for your help and feel free to close the issue.

**Comment by sileshn** [comment]
It does work. I am closing this hoping that your queries have been answered.
