### ISSUE TITLE
Installation error ERR: exit status 4294967295

### ISSUE THREAD

**Issue by arif-kun** [sileshn/ManjaroWSL#16]
### Requirements

- [X] Yes
- [ ] No

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Windows Build Number

Windows 11 Insider Preview Build 22000.120

### Kernel Version

5.10.16.3

### Repro Steps

Occurs on trying to install

### Expected Behavior

Should have installed just nicely like Ubuntu.

### Actual Behavior

ERR: exit status 4294967295
&exec.ExitError{ProcessState:(*os.ProcessState)(0xc00008eaa0), Stderr:[]uint8(nil)}

**Comment by sileshn** [comment]
Which folder are you trying to install to? I installed it yesterday on the same windows build. See my comments on issue 15

**Comment by arif-kun** [comment]
> Which folder are you trying to install to? I installed it yesterday on the same windows build. See my comments on issue 15
C:/VMs/ManjaroWSL

I have other VM images in this "VMs" folder but they are in their separate directory

**Comment by sileshn** [comment]
Then it should work. Try with the latest build

**Comment by arif-kun** [comment]
Installed without issues on build 22000.132
