### ISSUE TITLE
Unable to use ping without root

### ISSUE THREAD

**Issue by GonePh1shing** [sileshn/ManjaroWSL#19]
### Requirements

- [X] Yes
- [ ] No

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Windows Build Number

10.0.19042.1202

### Kernel Version

5.10.43

### Repro Steps

- Enable WSL feature
- Enable Virtual Machine feature
- Download and install Linux Kernel update 5.10.43
- Install as per readme
- Follow "How to setup" in the readme
- run 'ping 1.1.1.1'

Have confirmed I am able to use ping in a stock standard Ubuntu install from the Windows store. The Ubuntu install also returns the same kernel version. This has been tried on two separate machines running the same Windows build.

### Expected Behavior

Expect to see normal ping response. Would also expect to see kernel 5.10.43 in use instead of 4.4.0, but I suspect this may be an issue with WSL2 rather than this project.

### Actual Behavior

- 'ping 1.1.1.1' returns "ping: socket: Operation not permitted"
- 'sudo ping 1.1.1.1' works normally
- In Powershell, 'wsl --status' returns kernel version 5.10.43
- 'uname -srm' returns kernel version 4.4.0-19041

**Comment by GonePh1shing** [comment]
Was able to fix the kernel issue. Even though I had set the default WSL version to 2, both Manjaro and Ubuntu installed as ver 1. Running 'wsl --set-version Manjaro 2' fixed this.

However, the ping issue remains.

**Comment by GonePh1shing** [comment]
Thanks @sileshn, that worked perfectly.

**Comment by sileshn** [comment]
Close if issue is solved.
