### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by mioscape** [sileshn/ManjaroWSL#2]
![image](https://user-images.githubusercontent.com/43681888/102330888-b2bc0480-3fbc-11eb-8470-70105eaf822a.png)
 I have installed WSL Ubuntu before, but i uninstall it, is that make it installer manjaro error?

**Comment by mioscape** [comment]
Nevermind, I Forget to re-install Linux Kernel, thanks for this!

**Comment by sileshn** [comment]
I have updated the requirements in the readme file,

https://github.com/sileshn/ManjaroWSL/commit/fa9ffa22424b6705db380fe2bac841fb182e306f
