### ISSUE TITLE
Start in home directory and source .bashrc

### ISSUE THREAD

**Issue by zangman** [sileshn/ManjaroWSL#20]
When I run Manjaro.exe it opens a console in the same directory as the executable. Also it doesn't source `~/.bashrc`. Is there any way to have it `cd` to my home directory and source `.bashrc`?

**Comment by sileshn** [comment]
Add the CD command to your .bashrc . This is a feature of wsldl, so nothing I can do to change it.

**Comment by zangman** [comment]
Thanks - I had to replace WSL with a dedicated manjaro box, so can't test this at the moment. But I think the issue can be resolved by creating `~/.bash_profile` as you said above and filling it with the necessary commands. Thanks for your help!
