### ISSUE TITLE
Install Location

### ISSUE THREAD

**Issue by PeterKW** [sileshn/ManjaroWSL#21]
wsl --import MovedManjaro C:\WSL\Manjaro C:\temp\Manjaro.tar --version 2
[https://www.tenforums.com/tutorials/128152-set-default-user-windows-subsystem-linux-distro-windows-10-a.html](https://www.tenforums.com/tutorials/128152-set-default-user-windows-subsystem-linux-distro-windows-10-a.html )
I tried to move my Manjaro installed location to another drive with more storage but unfortunately WSL was struggling to export to the tar file as normal.

Is there a way to specify the install location for the downloaded Manjaro.exe program to install to so it's not using as much storage on my C drive? 

Hopefully want I'm trying to do makes sense. 
Thank you very much
Peter

**Comment by sileshn** [comment]
https://wsldl-pg.github.io/docs/Known-issues/

**Comment by sileshn** [comment]
Closing as issue seems to be fixed.
