### ISSUE TITLE
i ran the .exe file manjaro open up and type passwd and after that useradd -m -G wheel -s /bin/bash <username> but it keep say that -bash: syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by vamshirudra** [sileshn/ManjaroWSL#23]
****

**Comment by sileshn** [comment]
You have to replace <username> with the username that you want. For example if you want the username to be vamshirudra, then the command would be as shown below.

`useradd -m -G wheel -s /bin/bash vamshirudra`

**Comment by vamshirudra** [comment]
hey, another problem happens that when I'm I try to config default user when ran the command "Manjaro.exe config --default-user vamru", a pop up shows and saying "this app can't run on your PC" and then in cmd prompt results says access is denied.

**Comment by sileshn** [comment]
I need more information. Close this and open up a new issue using the issue form and provide all information requested there.
