### ISSUE TITLE
Re-Install problem

### ISSUE THREAD

**Issue by PeterKW** [sileshn/ManjaroWSL#25]
```
How to install
Make sure all the steps mentioned under "Requirements" are completed.
Set wsl2 as default. Run the command below in a windows cmd terminal.
wsl --set-default-version 2
Download installer zip.
Extract all files in zip file to same directory.
Run Manjaro.exe to Extract rootfs and Register to WSL
```

```
dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart

Deployment Image Servicing and Management tool
Version: 10.0.22000.1

Image Version: 10.0.22000.346

Enabling feature(s)
[==========================100.0%==========================]
The operation completed successfully.
```

I had a problem with WSL and had to re-install it from scratch. When I try and run Manjaro.exe it says the file can't be found? How should I futher debug what I am doing wrong?

```
\WSL\ManjaroWSL>Manjaro.exe
The system cannot find the file specified.

```

```
\WSL\ManjaroWSL>ls
Manjaro.exe  rootfs.tar.gz

```

**Comment by PeterKW** [comment]
The system cannot find the file specified.

[process exited with code 4294967295 (0xffffffff)]

**Comment by sileshn** [comment]
Please report issues using the form provided. I cannot help if I don't get the required information.

Googling the error code brings up similar issues discussed in the wsl github page. Go through them and see if any methods mentioned there work for you.

I personally haven't encountered this issue.
