### ISSUE TITLE
default inner uid-1000-user make new user uid 1001, which caused wslg dconf error

### ISSUE THREAD

**Issue by simsilver** [sileshn/ManjaroWSL#28]
for wslg write file as uid 1000, which is inner user builder's uid, new user we created will got errors like `"unable to create directory '/mnt/wslg/runtime-dir/dconf': Permission denied.  dconf will not work properly."` when running gedit.

a workaroud is to remove user builder and group builder, then change new users uid to 1000 and gid to 1000
`> wsl -u root`
`# userdel builder`
`# groupdel builder`
`# usermod -u 1000 <username>`
`# groupmod -g 1000 <username>`

then may need set default user again
`> Manjaro.exe config --default-user <username>`

**Comment by sileshn** [comment]
Try [this](https://onedrive.live.com/download?cid=A4DEE18D4370FE4F&resid=A4DEE18D4370FE4F%215842&authkey=ACodM3f3wQSmuNc") one.
