### ISSUE TITLE
Defaults to testing branch. Did not expect that.

### ISSUE THREAD

**Issue by sitedyno** [sileshn/ManjaroWSL#29]
### Requirements

- [X] Yes
- [ ] No

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Windows Build Number

Microsoft Windows [Version 10.0.19042.1466]

### Kernel Version

5.10.60.1

### Repro Steps

bat /etc/pacman-mirrors.conf
```
##
## /etc/pacman-mirrors.conf
##

## Branch Pacman should use (stable, testing, unstable)
Branch = testing
```

### Expected Behavior

bat /etc/pacman-mirrors.conf
```
##
## /etc/pacman-mirrors.conf
##

## Branch Pacman should use (stable, testing, unstable)
Branch = stable
```

This is not a big deal, though I was surprised to realize I was on testing. Maybe a mention in the README that testing branch is default, or perhaps a query during installation on which to use?

Thank you for putting Manjaro on WSL, really cool!

### Actual Behavior

The installer seems to default to testing.

**Comment by sileshn** [comment]
Its not an error. I have done that intentionally.

**Comment by sileshn** [comment]
https://github.com/sileshn/ManjaroWSL/commit/efbb1d342975728ad88079146b5203ad97f6fb37
