### ISSUE TITLE
Bash "error" on new install

### ISSUE THREAD

**Issue by shinji257** [sileshn/ManjaroWSL#30]
### Requirements

- [X] Yes
- [ ] No

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Windows Build Number

10.0.22000.527

### Kernel Version

5.10.60.1

### Repro Steps

First launch of fresh install for Manjaro.  Used package download released just hours ago of this issue ticket.

Throws a script message "-bash: [: -le: unary operator expected" on first launch but seems to proceed normally.  May be referencing an empty variable?

### Expected Behavior

I wouldn't expect the message to come up at all.

### Actual Behavior

Produces the message.  May not actually impact anything.

**Comment by sileshn** [comment]
I have not tried running this on windows 11 as I am still on windows 10. I can't seem to reproduce that error on my machine. Can you send me a screenshot?

**Comment by sileshn** [comment]
I will need to add additional checks for windows 11 and Windows terminal. Startup script runs into issues in either scenario. Thanks for the feedback.

**Comment by azye** [comment]
I can attest that I ran this on windows 10 yesterday with latest build and also got this error on initial startup. I did an install maybe 2 weeks ago and did not see this issue then, so seems to be recently introduced
