### ISSUE TITLE
Default pacman mirror branch may be set to testing instead of stable by default.

### ISSUE THREAD

**Issue by FerranMontoliu** [sileshn/ManjaroWSL#32]
### Requirements

- [X] Yes
- [ ] No

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Windows Build Number

Microsoft Windows [Version 10.0.19044.1503]

### Kernel Version

5.10.60.1

### Repro Steps

1. Complete requirements and follow the steps to install manjaro from this repo.
3. Install `yay`.
4. Run `yay` to update all system dependencies.

### Expected Behavior

All dependencies updated and nothing breaks.

### Actual Behavior

Some dependencies are broken because the last `systemd` version from the testing branch needs `glibc 2.34` but yay updated my `glibc` to `glibc 2.35`.

Then if I reboot the system, it boots but I cannot do much. Can't execute `vi`, `vim`, `dockerd`, `kubectl`, etc.

<hr/>

When this happened, I checked which branch I was on for the pacman mirrors and realized I was in the `testing` branch.

To my knowledge, I did not set this manually, so this may come by default. It might be possible, though, that I set this manually some months ago and don't recall it.

In case this really comes by default, I believe it would be better to set the branch by default to `stable` to avoid this kind of issues.

<hr/>

## Temporal solution:

Run the following command to reset pacman mirrors to default: `sudo pacman-mirrors --country all --api --protocols all --set-branch stable && sudo pacman -Syyu`

**Comment by sileshn** [comment]
It's not an issue. Builds prior to 21 Feb used testing branch by default. Builds after 21st reverted to stable branch

**Comment by FerranMontoliu** [comment]
> It's not an issue. Builds prior to 21 Feb used testing branch by choice. Builds after 21st reverted to stable branch

Thank you for the rapid answer, I was using a release from October 2021.

**Comment by FerranMontoliu** [comment]
For anyone encountering this issue with Manjaro asking for `glibc 2.34`, know that, by default, Manjaro does not update `glibc`, and this can potentially break your system because some programs may update their dependencies to use a newer version.

To change this behaviour you can do the following steps:
1. Run `sudo vim /etc/pacman.conf`.
2. Look for a line that reads `IgnorePkg = glibc`.
3. Comment this line adding a `#` at its beginning and save the file.

Now you can update `glibc` either with `yay` or `pacman`.

**Comment by sitedyno** [comment]
I'm super confused. Not sure what happened.

I changed to stable back on Jan 31st, updated and there were no problems.

Today I update `sudo pacman -Syu` and after restarting I see `vim: /usr/lib/libc.so.6: version `GLIBC_2.34' not found (required by vim)`. I ASSume that means the system wants glibc 2.34, but pacman wants to update from 2.33 to 2.35. Trying to install anything results in `error: GPGME error: Invalid crypto engine` when pacman tries to verify package signature.

Advice? I can restart if needed, but feelsBadMan.

**Comment by FerranMontoliu** [comment]
@sitedyno 

> Advice? I can restart if needed, but feelsBadMan.

In my case, I had a backup from a couple of months ago and I switched to that.

---

What could have happened to you is that, when updating the system, you may have ignored the glibc update (since it is the default behaviour). Here you can find more info about that:

> For anyone encountering this issue with Manjaro asking for `glibc 2.34`, know that, by default, Manjaro does not update `glibc`, and this can potentially break your system because some programs may update their dependencies to use a newer version.
> 
> To change this behaviour you can do the following steps:
> 
> 1. Run `sudo vim /etc/pacman.conf`.
> 2. Look for a line that reads `IgnorePkg = glibc`.
> 3. Comment this line adding a `#` at its beginning and save the file.
> 
> Now you can update `glibc` either with `yay` or `pacman`.

---

A possible fix may be to download `glibc 2.35` binary manually from the mirror's stable branch from your Windows host, and then accessing to your Manjaro WSL through the network (you can do that by putting `\\wsl$` in the Windows explorer folder path) and then putting it where it should be.

I am now working with `glibc 2.35` installed in my system with all the programs updated to their last version from the stable branch and everything works, I think it is backwards compatible with the 2.34 version.
