### ISSUE TITLE
Basically a Question - Disk Read Write Performance

### ISSUE THREAD

**Issue by afzl-wtu** [sileshn/ManjaroWSL#33]
Today I installed latest Release on Windows 11 with latest kernel following all your mentioned steps.
I see a drive titled as Linux as shown below:
![image](https://user-images.githubusercontent.com/64379149/157181641-6bb220d9-8e00-41c1-8eff-dd9720f6e170.png)

Further when I run Manjaro inside CMD it starts not from home user directory but where the manjaro.exe is placed on Windows Dir.
![image](https://user-images.githubusercontent.com/64379149/157182052-2b603f80-4527-4b47-8842-de54511caa12.png)

But normally Linux terminal starts from Home Directory, I mean /home/user/

1.  Is it for performance reasons?
2.  I see a ext4.vhdx file where Manjaro is installed. It means Manjaro runs from a virtual file not from Raw Disk (It means WSL 2 will be always slower as compared to Native Linux on bare metal). There is a Software called ext2fsd which allows to mount ext4 partition mounting. Can I convert vhdx to ext4 partition for faster speed?
3. Can I gain same native performance if I install my softwares (i.e, flutter android studio, gradle) in /mnt/c/Users/afzlw/Documents/@Apps/ManjaroWSL (NTFS) instead of /home/user/ (inside virtual ext4 system)?

Or should I go for Manjaro XFCE native?
Thanks a lot.

**Comment by sileshn** [comment]
1. No. Its a feature of wsldl. So you'll need to check with its creator, yuk7.
2. Yes. It will be slower. No you cannot convert the disk format AFAIK.
3. Nope.

**Comment by afzl-wtu** [comment]
> 1. No. Its a feature of wsldl. So you'll need to check with its creator, yuk7.
> 2. Yes. It will be slower. No you cannot convert the disk format AFAIK.
> 3. Nope.

Last question and most important: Should I place my files in /mnt/c/Users/afzlw/Documents/@Apps/ManjaroWSL (NTFS) or /home/user/ (inside virtual ext4 system)?
which one is faster in read write? 
If c drive is mounted through network drive then it must be slow than writting in virtual ext4.
But if NTFS drives or directly mounted inside WSL2 then it must perform better than writting in vhdx (or virtual ext4).
