### ISSUE TITLE
Install `wslu` and `xdg-utils` by default.

### ISSUE THREAD

**Issue by izznatsir** [sileshn/ManjaroWSL#34]
### Requirements

- [X] Yes
- [ ] No

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Windows Build Number

Version 10.0.19044.1620

### Kernel Version

5.10.102.1-microsoft-standard-WSL2

### Repro Steps

When I try to login on Github CLI, it fails to automatically open the default browser on Windows.

### Expected Behavior

The default browser on Windows is successfully opened.

### Actual Behavior

It fails to automatically open default web browser on Windows side. the cause is that `xdg-open` and `wslview` are missing. `xdg-open` to open default browser and `wslview` to act as proxy by setting it as the default browser on linux via `BROWSER` environment variable.

**Comment by izznatsir** [comment]
The solution is to install `xdg-utils` and `wslu` package. Then, set `BROWSER` environment variable with `wslview` as the value.
```bash
export BROWSER="wslview"
```

**Comment by sileshn** [comment]
How is this an issue? If you install the required packages, you'll get if to work. Wslu cannot be installed on arch based distros. You'll have to add a third party repo or compile from source. 

What you have mentioned is for the user to do.

**Comment by izznatsir** [comment]
Users who come from Ubuntu WSL already get this out of the box. It's about expectation. 

If you believe that it should be handled by the users that's ok too. But, some casual users might be surprised.

Feel free to close the issue, thanks.
