### ISSUE TITLE
Stays "Running" after logging out.

### ISSUE THREAD

**Issue by mehmetsen73** [sileshn/ManjaroWSL#35]
### Requirements

- [X] Yes
- [ ] No

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Windows Build Number

Microsoft Windows [Version 10.0.19044.1679]

### Kernel Version

5.10.102.1

### Repro Steps

After logging out of Manjaro, at windows terminal "wsl -l -v" shows the instance as "Running".

### Expected Behavior

Ubuntu distro stops after the user logs out.

### Actual Behavior

>wsl --list -v
  NAME       STATE           VERSION
* Ubuntu     Stopped         2
  Manjaro    Running         2

**Comment by sileshn** [comment]
how are you logging out?

**Comment by iboB** [comment]
@mehmetsen73 did you wait a while?

If you type `exit` from the terminal, it takes some seconds for the vm to properly shut down.
