### ISSUE TITLE
Please rename the project

### ISSUE THREAD

**Issue by fhdk** [sileshn/ManjaroWSL#36]
The project name implies it is created by Manjaro Team.

You should rename it accordingly e.g. WSL for Manjaro - to make it clear to users that the project is not officially connected to Manjaro.

Best regards.

**Comment by sileshn** [comment]
It doesn't say its created by Manjaro team anywhere. Unless someone from the Manjaro team has any issues with it naming and contacts me about it, I cannot entertain your request.

**Comment by fhdk** [comment]
I am a member of the Manjaro Team - please honor the request.

https://manjaro.org/team/
