### ISSUE TITLE
Add sudo to default install

### ISSUE THREAD

**Issue by Zackptg5** [sileshn/ManjaroWSL#4]
Fantastic work! Thought I would have to go back to dual booting since xrdp took a dump with hyper-v but this saved the day. Could you add sudo with the `# (%wheel ALL=(ALL) ALL)` line uncommented in the sudoers file for more regular users? There are some configure and build scripts that rely on a regular user being able to drop in and out of root (install packages with pacman and pamac for aur) where sudo is needed.

If there's another/better way of doing it though let me know, thanks!

**Comment by sileshn** [comment]
Sure. Will add it today

**Comment by sileshn** [comment]
https://github.com/sileshn/ManjaroWSL/commit/fcb7a391b0441b5e719ff85a3b61f86783aa6bcd

You can build from source to get the change or download the next release when I put it out.

**Comment by Zackptg5** [comment]
Awesome, thanks!
