### ISSUE TITLE
ERROR: Installation Failed!  HRESULT:0x8007019e

### ISSUE THREAD

**Issue by changrui** [sileshn/ManjaroWSL#5]
```
Using: F:\Manjaro\rootfs.tar.gz
Installing...
ERROR:Installation Failed!
HRESULT:0x8007019e
Press any key to continue...
```

**Comment by sileshn** [comment]
Follow instructions in the readme file. You may have not enabled Windows Subsystem for Linux

**Comment by changrui** [comment]
Sorry, the same error message on powershell (Admin).

**Comment by sileshn** [comment]
This is the procedure. Run the commands below in PS

dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart

Install wsl kernel. Link is available in the readme

Open cmd and set wsl2 as default.

Unzip Manjaro.zip and double click on Manjaro.exe.

If it doesn't work, there is something missing from your end. Will need more information

**Comment by changrui** [comment]
ErrorMessage： ·HRESULT:0x800701bc·。

**Comment by sileshn** [comment]
https://github.com/Microsoft/WSL/issues/2982

HRESULT:0x8007019e error is usually when Windows subsystem for linux is not enabled

**Comment by sileshn** [comment]
HRESULT:0x800701bc

You have not installed wsl kernel. Please read the instructions and follow them.

**Comment by changrui** [comment]
Yes， thanks a lot.

> HRESULT:0x800701bc
> 
> You have not installed wsl kernel. Please read the instructions and follow them.

**Comment by sileshn** [comment]
If your issue is solved, close this.

**Comment by sileshn** [comment]
Closing this as issue seems to be solved
