### ISSUE TITLE
Error Installation directory not found

### ISSUE THREAD

**Issue by Pingu69** [sileshn/ManjaroWSL#6]
When I run the exe I get this 
````ERROR:
Installation directory not found: C:\Users\Petar\AppData\Local\Temp\Rar$EXa0.770.
Make sure it exists or reinstall.
ERROR
HRESULT:0x80004005
Press any key to continue...
````
I made the mistake to run the exe inside winrar, how can I reinstall correctly?

**Comment by sileshn** [comment]
Read the directions in the readme file

**Comment by Pingu69** [comment]
Thanks, should have read the readme more carefully :sweat_smile:
