### ISSUE TITLE
'kernel too old' error

### ISSUE THREAD

**Issue by guai** [sileshn/ManjaroWSL#9]
win 10 enterprise 20H2 build 19042.906
ManjaroWSL-20210401
```
C:\Users\guai>wsl -d manjaro
FATAL: kernel too old
```

**Comment by PhyX-Meow** [comment]
You should update your kernel maybe, the wsl filesystem DOES NOT CONTAIN ANY LINUX KERNEL.

**Comment by guai** [comment]
@PhyX-Meow, can you pls point me how do I do it?

**Comment by PhyX-Meow** [comment]
You can try `wsl --update`, or manually download from somewhere of MS document.........

**Comment by PhyX-Meow** [comment]
https://aka.ms/wsl2kernel
Here it is

**Comment by PhyX-Meow** [comment]
Seems `wsl --update` is only available in insider preview at the moment

**Comment by guai** [comment]
Got it working after `wsl --set-version Manjaro 2`
Thanks, @PhyX-Meow
